- name: baremetal - add_host to run time inventory for master group
  add_host:
    groups:
      - master
    name: "{{ item }}"
    ansible_user: "{{bm_node_username}}"
    ansible_password: "{{bm_node_password}}"
    ansible_become: True
    ansible_become_password: "{{bm_node_password}}"
  with_items: "{{ nodeIPs[0] }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth == 'False'

- name: baremetal - add_host to run time inventory for master group
  add_host:
    groups:
      - master
    name: "{{ item }}"
    ansible_user: "{{bm_node_username}}"
    ansible_private_key_file: "{{bm_key_path}}"
    ansible_become: True
  with_items: "{{ nodeIPs[0] }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth  | bool

#- debug:
#    msg: System{{ nodeIPs |  first}} has uuid {{ nodeIPs[0]}} and {{nodeIPs}} and bm_nodeIPs {{bm[0]}} and {{bm}}
#  vars:
#    nodeIPs: ['192.168.122.199','192.168.122.131','192.168.122.117']
#    bm: "{{bm_nodeIPs}}"

- name: baremetal - add_host to run time inventory for baremetal_nodes group
  add_host:
    name: "{{item}}"
    vm_hostname: "{{bm_node_prefix}}{{my_idx+1}}"
    ansible_user: "{{bm_node_username}}"
    ansible_password: "{{bm_node_password}}"
    ansible_become: True
    ansible_become_password: "{{bm_node_password}}"
    groups:
      - baremetal_nodes
  loop: "{{ bm_nodeIPs }}"
  loop_control:
    index_var: my_idx
  when:
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth == 'False'

- name: baremetal - add_host to run time inventory for baremetal_nodes group
  add_host:
    name: "{{item}}"
    vm_hostname: "{{bm_node_prefix}}{{my_idx+1}}"
    ansible_user: "{{bm_node_username}}"
    ansible_private_key_file: "{{bm_key_path}}"
    ansible_become: True
    groups:
      - baremetal_nodes
  loop: "{{ bm_nodeIPs }}"
  loop_control:
    index_var: my_idx
  when:
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth  | bool

- name: baremetal - add_host to run time inventory for kubernetes group
  add_host: groups=kubernetes
            name={{ item }}
            ansible_user={{bm_node_username}}
            ansible_password={{bm_node_password}}
            ansible_become=True
            ansible_become_password={{bm_node_password}}
  with_items: "{{ nodeIPs }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth == 'False'

- name: baremetal - add_host to run time inventory for kubernetes group
  add_host: groups=kubernetes
            name={{ item }}
            ansible_user={{bm_node_username}}
            ansible_private_key_file={{bm_key_path}}
            ansible_become=True
  with_items: "{{ nodeIPs }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth  | bool

- name: baremetal - add_host to run time inventory for worker group
  add_host: name={{ item }}
            groups=worker
            ansible_user={{bm_node_username}}
            ansible_password={{bm_node_password}}
            ansible_become=True
            ansible_become_password={{bm_node_password}}
  with_items: "{{ nodeIPs[1:] }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth == 'False'

- name: baremetal - add_host to run time inventory for worker group
  add_host: name={{ item }}
            groups=worker
            ansible_user={{bm_node_username}}
            ansible_private_key_file={{bm_key_path}}
            ansible_become=True
  with_items: "{{ nodeIPs[1:] }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count > 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth  | bool


- name: baremetal - if count is 1 than add that host to all groups
  add_host:
    name: "{{ item }}"
    ansible_user: "{{bm_node_username}}"
    ansible_password: "{{bm_node_password}}"
    ansible_become: True
    ansible_become_password: "{{bm_node_password}}"
    groups:
      - kubernetes
      - master
  with_items: "{{ nodeIPs }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count == 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth == 'False'

- name: baremetal - if count is 1 than add that host to all groups
  add_host:
    name: "{{ item }}"
    ansible_user: "{{bm_node_username}}"
    ansible_private_key_file: "{{bm_key_path}}"
    ansible_become: True
    groups:
      - kubernetes
      - master
  with_items: "{{ nodeIPs }}"
  vars:
    nodeIPs: "{{bm_nodeIPs}}"
  when:
    - bm_nodeIPs.count == 1
    - cluster_os == 'centos'
    - infra_type == 'baremetal'
    - bm_key_based_auth  | bool