apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
#          value: crate-datasource,grafana-clock-panel,grafana-worldmap-panel
          value: grafana-clock-panel,grafana-worldmap-panel
        image: grafana/grafana
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
