apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapusher-deployment
  labels:
    app: datapusher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datapusher
  template:
    metadata:
      labels:
        app: datapusher
    spec:
      containers:
      - name: datapusher
        image: clementmouchet/datapusher
        ports:
        - containerPort: 8800
---
apiVersion: v1
kind: Service
metadata:
  name: datapusher-service
  labels:
    app: datapusher
spec:
  ports:
  - protocol: TCP
    port: 8800
    targetPort: 8800
  selector:
    app: datapusher

