apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-pv01
  namespace: {{ k8s_namespace }}
  labels:
    type: nfs
spec:
#  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef: 
    namespace: {{ k8s_namespace }}
    name: postgres-replica-postgres-replica-0
  nfs:
    server: {{ ansible_default_ipv4.address }}
    path: /opt/ckan/postgres-replica/postgres-replica-pv01
    readOnly: false
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-replica-postgres-replica-0
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
