site_name: kubernetes-in-FiwareLab
site_url: https://kubernetes-in-fiwarelab.readthedocs.io/en/latest/
site_description: To deploy kubernetes on Fiware-Lab using ansible.
repo_url: https://github.com/Fiware-Community/kubernetes-in-FiwareLab
edit_uri: 'edit/main/docs/'
docs_dir: docs
theme: readthedocs
markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_operations.css"]
nav:
  - Home: 'index.md'
  - 'User & Programmers Manual':
    - 'Using Ansible': 'quick_start_guide.md'
  - 'Installation & Administration Manual':
    - 'Install Ansible': 'install-ansible.md'
    - 'Passwordless SSH': 'passwordless-ssh.md'
    - 'Root Access': 'root-access.md'
    - 'Setup Firewalld': 'setup-firewalld.md'
    - 'Update Kernel': 'update-kernel.md'
  - 'Persistent Storage':
    - 'Using Persitent Storage': 'Persistent Storage/README.md'
  - 'Network Configuration Options':
    - 'Using Network Configuration Options': 'Network Options/README.md'
  - 'Fiware GEs setup':
    - 'Fiware GEs setup': 'Fiware GEs/README.md'
  - 'Security Options':
    - 'Using Security Options': 'Security Options/README.md'
