apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - image: rhcayadav/broker:v2.11
        name: broker
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /config.json
          subPath: config.json
          name: broker-configmap
      restartPolicy: Always
      volumes:
      - name: broker-configmap
        configMap:
          name: broker-configmap
          defaultMode: 0777


status: {}

