apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cloud-worker
  name: cloud-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cloud-worker
    spec:
      containers:
      - image: rhcayadav/worker:4.2
        name: cloud-worker
        resources: {}
        volumeMounts:
        - mountPath: /config.json
          subPath: config.json
          name: cloud-worker-configmap
        - mountPath: /tmp
          name: worker-claim2
        - mountPath: /var/run/docker.sock
          name: worker-claim3
      restartPolicy: Always 
      volumes:
      - name: cloud-worker-configmap
        configMap:
          name: cloud-worker-configmap
          defaultMode: 0777
      - name: worker-claim2
        hostPath:
          path: /tmp
      - name: worker-claim3
        hostPath:
          path: /var/run/docker.sock
          type: File
status: {}
