apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: designer
  name: designer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: designer
    spec:
      containers:
      - image: rhcayadav/designer:v3.2
        name: designer
        ports:
        - containerPort: 80
        - containerPort: 1030
        resources: {}
        volumeMounts:
        - mountPath: /app/config.json
          subPath: config.json
          name: designer-configmap
      restartPolicy: Always
      volumes:
      - name: designer-configmap
        configMap:
          name: designer-configmap
          defaultMode: 0777
status: {}

