apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
      - image: rhcayadav/master:v2.3
        name: master
        ports:
        - containerPort: 1060
        resources: {}
        volumeMounts:
        - mountPath: /config.json
          subPath: config.json
          name: master-configmap
      restartPolicy: Always
      volumes:
      - name: master-configmap
        configMap:
          name: master-configmap
          defaultMode: 0777
status: {}
