apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgis
    spec:
      containers:
      - image: rhcayadav/postgis:v1.1
        name: postgis
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
