apiVersion: v1
kind: Service
metadata:
  namespace: {{ k8s_namespace }}
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: grafana
  externalIPs:
  - {{ ansible_default_ipv4.address }}
