apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo2-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/sth-mongo/vol/0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo2-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
