apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-perm-data-pv0
  labels:
    type: nfs
spec:
#  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: postgres-perm-data-postgres-0
  nfs:
    path: /opt/ckan/postgres/perm-data/
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-perm-data-postgres-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
