apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-pv01
  labels:
    type: nfs
spec:
#  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: postgres-replica-postgres-replica-0
  nfs:
    path: /opt/ckan/postgres-replica/postgres-replica-pv01
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-replica-postgres-replica-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
