apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster2-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-redis-cluster2-2
  nfs:
    path: /opt/qp/redis/vol/2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-cluster2-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
