apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cluster2-pv4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-redis-cluster2-4
  nfs:
    path: /opt/redis/vol/4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-cluster2-4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
