apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-1
  namespace: {{ k8s_namespace }}
  labels:
    app: galera-ss
    podindex: "1"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    namespace: {{ k8s_namespace }}
    name: mysql-datadir-galera-ss-1
  nfs:
    path: /opt/draco/galera-1/datadir
    server: {{ ansible_default_ipv4.address }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-datadir-galera-ss-1
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: galera-ss
      podindex: "1"

