apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckandata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: ckandata
  nfs:
    path: /opt/ckan/ckandata/

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckandata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
