apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckanconfig
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: ckanconfig
  nfs:
    path: /opt/ckan/ckanconfig/

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckanconfig
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
