kind: Service
apiVersion: v1
metadata:
  name: cepheus
spec:
  ports:
  - name: "8080"
    port: 8090
    targetPort: 8080
  - name: "8081"
    port: 8091
    targetPort: 8081
  selector:
    app: cepheus
  externalIPs:
