apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cepheus
    app: cepheus
  name: cepheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cepheus
        app: cepheus
    spec:
      containers:
      - image: orangeopensource/fiware-cepheus
        name: cepheus
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}        
      restartPolicy: Always      
status: {}
