apiVersion: v1
kind: Service
metadata:
  name: solrcluster
  namespace: {{ k8s_namespace }}
  labels:
    app: solr-app
spec:
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ k8s_namespace }}
  name: solr-service
  labels:
    app: solr-app
spec:
  ports:
  - protocol: TCP
    port: 8983
    targetPort: 8983
  #type: LoadBalancer
  selector:
    app: solr-app
  externalIPs:
  - {{ ansible_default_ipv4.address }}
