apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: data-crate-0
  nfs:
    path: /opt/cratedb/vol/0
    server: 11.0.0.23
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-crate-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
