---
- name: create kubernetes vms on openstack/aws/baremetal with floating ips using cloud-config.yaml
  gather_facts: true
  hosts: localhost
  roles:
    - { role: vm-deploy,
        when: (k8s_enable_kubernetes  | bool) and  (infra_type == 'openstack' or infra_type == 'AWS' or infra_type == 'baremetal') }
  environment:
      OS_AUTH_URL: "{{ op_OS_AUTH_URL }}"
      OS_USERNAME: "{{ op_OS_USERNAME }}"
      OS_PASSWORD: "{{ op_OS_PASSWORD }}"
      OS_PROJECT_NAME: "{{ op_OS_PROJECT_NAME }}"
      OS_USER_DOMAIN_NAME: "{{ op_OS_USER_DOMAIN_NAME }}"
      OS_PROJECT_DOMAIN_NAME: "{{ op_OS_PROJECT_DOMAIN_NAME }}"
      #OS_REGION_NAME: "{{ op_OS_REGION_NAME }}"
      AWS_ACCESS_KEY_ID: "{{ ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ SECRET_ACCESS_KEY }}"
      AWS_REGION: "{{ REGION }}"

#- name: create kubernetes vms on aws with public ips
#  gather_facts: true
#  hosts: localhost
#  roles:
#    - { role: aws-vm-deploy,
#        when: (k8s_enable_kubernetes  | bool) and  (infra_type == 'AWS')}
#  environment:
#      AWS_ACCESS_KEY_ID: "{{ ACCESS_KEY_ID }}"
#      AWS_SECRET_ACCESS_KEY: "{{ SECRET_ACCESS_KEY }}"
#      AWS_REGION: "{{ REGION }}"

#- name: create baremetal with iPs using cloud-config.yaml
#  gather_facts: true
#  hosts: localhost
#  tasks:
#    - import_role:
#        name: baremetal
#      when: (k8s_enable_kubernetes  | bool) and  (infra_type == 'baremetal')

- name: set hostname for baremetal/vm nodes
  gather_facts: true
  hosts: baremetal_nodes
  tasks:
    - name: Grant centos user passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: 'centos ALL=(ALL) NOPASSWD: ALL'
      when: ansible_os_family == 'RedHat'

    - name: Grant ubuntu user passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
      when: ansible_os_family == 'Debian'
    - command: hostnamectl set-hostname {{ vm_hostname }}
      when: (k8s_enable_kubernetes  | bool) and  (infra_type == 'baremetal')

- name: Apply kubernetes-common role for common tasks
  gather_facts: true
  hosts:
    - kubernetes
  roles:
    - role: kubernetes-common
      when:
        - k8s_enable_kubernetes  | bool

- name: Apply kubernetes master role for kubernetes master tasks
  gather_facts: true
  hosts:
    - master
  roles:
    - role: master
      when:
        - k8s_enable_kubernetes  | bool

- name: Apply kubernetes worker role for kubernetes worker tasks
  gather_facts: true
  hosts:
    - worker
  roles:
    - role: worker
      when:
        - op_count > 1
        - k8s_enable_kubernetes  | bool

- name: Apply kubernetes-post-deploy role for kubernetes post deploy check
  gather_facts: true
  hosts:
    - master
  roles:
    - role: kubernetes-post-deploy
      when:
        - k8s_enable_kubernetes  | bool

- name: install pip  setuptools and openshift for k8 ansible module
  gather_facts: true
  hosts:
    - master
  pre_tasks:
    - yum:
        name: python-pip
        state: present
      become: True
      when: ansible_os_family == 'RedHat'
    - apt:
        name: python3-pip
        state: present
      become: True
      when: ansible_os_family == 'Debian'
    - name: Ensure wheel is installed.
      pip:
        name: wheel
        state: present
    - name: Ensure OpenShift client is installed.
      pip:
        name: setuptools
        state: latest
    - name: Ensure OpenShift client is installed.
      pip:
        name: openshift
        state: present

- name: install helm and prom and grafana
  gather_facts: true
  hosts:
    - master
  roles:
    - role: ansible-kube-helm
      when:
        - k8s_enable_kubernetes  | bool

- name: install orion
  gather_facts: true
  hosts:
    - master
  roles:
    - role: orion
      when:
        - enable_orion  | bool

- name: install sth-comet
  gather_facts: true
  hosts:
    - master
  roles:
    - role: sth-comet
      when:
        - enable_sth_comet  | bool

- name: install cygnus-sth
  gather_facts: true
  hosts:
    - master
  roles:
    - role: cygnus-sth
      when:
        - enable_cygnus_sth  | bool
        - enable_sth_comet  | bool

- name: install 
  gather_facts: true
  hosts:
    - master
  roles:
    - role: iotagent
      when:
        - enable_iotagent  | bool
        - enable_orion  | bool

- name: install quantumleap
  gather_facts: true
  hosts:
    - master
  roles:
    - role: quantumLeap
      when:
        - enable_quantumleap  | bool

- name: install draco
  gather_facts: true
  hosts:
    - master
  roles:
    - role: draco
      when:
        - enable_draco  | bool

- name: install ckan
  gather_facts: true
  hosts:
    - master
  roles:
    - role: ckan
      when:
        - enable_ckan  | bool

