---
# tasks file for iotagent

- name: Create a k8s namespace
  k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: yes

- name: create k8 iotagent service
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/kube_svc_iotagent-json.yaml') }}"
    wait: yes
    apply: yes

- name: create k8 iotagent deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/kube_iotagent-json_deployment.yaml') }}"
    wait: yes
    apply: yes
    wait_timeout: 300
    wait_condition:
      type: Available
      status: True
