apiVersion: v1
kind: Service
metadata:
  namespace: {{ k8s_namespace }}
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ckan
  name: ckan
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: ckan
  externalIPs:
  - {{ ansible_default_ipv4.address }}
