apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckanconfig
  namespace: {{ k8s_namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: {{ k8s_namespace }}
    name: ckanconfig
  nfs:
    path: /opt/ckan/ckanconfig/
    server: {{ ansible_default_ipv4.address }}
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckanconfig
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
