kind: Service
apiVersion: v1
metadata:
  namespace: {{ k8s_namespace }}
  name: crate-external-service
  labels:
    app: crate
spec:
  ports:
  - port: 4200
    name: crate-web
  - port: 5432
    name: postgres
  selector:
    app: crate
  externalIPs:
  - {{ ansible_default_ipv4.address }}
