apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-0
  namespace: {{ k8s_namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: {{ k8s_namespace }}
    name: data-crate-0
  nfs:
    path: /opt/cratedb/vol/0
    server: {{ ansible_default_ipv4.address }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-crate-0
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
