apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ k8s_namespace }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: iotagent-json
  name: iotagent-json
spec:
  selector:
    matchLabels:
      app: iotagent-json
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: iotagent-json
        app: iotagent-json
    spec:
      containers:
      - env:
        - name: IOTA_CB_HOST
          value: orion.{{ k8s_namespace }}.svc.cluster.local
        - name: IOTA_CB_PORT
          value: "1026"
        - name: IOTA_HTTP_PORT
          value: "7896"
        - name: IOTA_MONGO_DB
          value: iotagentjson
        - name: IOTA_MONGO_HOST
          value: mongo.{{ k8s_namespace }}.svc.cluster.local:27017
        - name: IOTA_MONGO_PORT
          value: "27017"
        - name: IOTA_NORTH_PORT
          value: "4041"
        - name: IOTA_REGISTRY_TYPE
          value: mongodb
        - name: IOTA_MONGO_REPLICASET
          value: rs0
        image: "fiware/iotagent-json:{{ iot_version }}"
        name: fiware-iot-agent
        ports:
        - containerPort: 4041
        - containerPort: 7896
        resources: {}
      restartPolicy: Always
status: {}
