kind: Service
apiVersion: v1
metadata:
  name: orion
  namespace: {{ k8s_namespace }}
spec:
  ports:
  - name: "1026"
    port: 1026
    targetPort: 1026
  selector:
    app: orion
  externalIPs:
  - {{ ansible_default_ipv4.address }}
