apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv0
  namespace: {{ k8s_namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: {{ k8s_namespace }}
    name: db-mongo-0
  nfs:
    server: {{ ansible_default_ipv4.address }}
    path: /opt/orion/data/vol/0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-0
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
