apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/3
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-mongo-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi